from tkinter import *
from tkinter import ttk
from tkcalendar import DateEntry
from tkinter import messagebox
from PIL import Image, ImageTk
import mysql.connector as dic
root = Tk()
root.geometry("600x600")
# root.config(bg="grey")
# root.maxsize(width=600, height=600)
root.minsize(width=600, height=600)
# root.iconphoto(True, PhotoImage(file="logo.png"))
root.title("CSC")
hr = Image.open("harihar.png")
baba = hr.resize((300, 300))
bh = ImageTk.PhotoImage(baba)
image = Image.open("csc.png")
lg = Image.open("logo.png")
myph = Image.open("my.png")
bnt = Image.open("Bintu.png")
bintu = bnt.resize((105, 120))
bj = ImageTk.PhotoImage(bintu)
myrs = myph.resize((105, 120))
myp = ImageTk.PhotoImage(myrs)
reslg = lg.resize((40, 40))
pl = ImageTk.PhotoImage(reslg)
resimg = image.resize((200, 90))
photo = ImageTk.PhotoImage(resimg)
f1 = LabelFrame(root, text=" Personal ", bg="yellow", fg="green", height=220)
f1.pack(fill="both", padx=10, pady=10)
f2 = LabelFrame(root, borderwidth=2)
f2.pack(pady=10)
plg = Label(f2, image=pl)
plg.pack(side=LEFT)
# Button(root, text="Home", relief=RIDGE).pack(side=TOP)
f5 = LabelFrame(root, height=300)
f5.pack(fill="both", padx=10)
Label(f5, image=bh).pack()
# f3=LabelFrame(root, text=" Preview ", height=153)
# f3.pack(fill="both", padx=10)
f4 = LabelFrame(root, height=60)
f4.pack(side=BOTTOM, anchor="s", pady=10)
csc = Label(root, image=photo)
csc.pack(side=BOTTOM)
Label(root, image=myp).place(x=55, y=420)
Label(root, image=bj).place(x=440, y=420)
def raise_frame(frame):
    frame.tkraise()
for frame in (f1, f2, f4, f5):
    frame.place()
Button(f1, text='Go to frame 2', command=lambda:raise_frame(f2)).pack()
Label(f1, text='FRAME 1').pack()

# newin = Toplevel(root)
# newin.geometry("600x240")
# newin.title("Data Entry")
# newin.config(bg="green")
# newin.config()    \
# f1 = LabelFrame(root, text=" Personal ", bg="yellow", fg="green", height=220)
# f1.pack(fill="both", padx=10, pady=10)
name = Label(f1, text="Name", bg="yellow")
name.place(x=170, y=10)
fname = Label(f1, text="Father/Husband Name", bg="yellow")
fname.place(x=120, y=35)
sname = Label(f1, text="Service Name", bg="yellow")
sname.place(x=160, y=60)
appln = Label(f1, text="Application No.", bg="yellow")
appln.place(x=160, y=85)
sts = Label(f1, text="Status", bg="yellow")
sts.place(x=160, y=110)
date = Label(f1, text="Submiting Date", bg="yellow")
date.place(x=150, y=135)
namevalue = StringVar()
fnamevalue = StringVar()
snamevalue = StringVar()
apvalue = StringVar()
stsvalue = StringVar()
datevalue = StringVar()
namentry = Entry(f1, relief=RIDGE, textvariable=namevalue, borderwidth=2)
namentry.place(x=250, y=10)
fnamentry = Entry(f1, relief=RIDGE, textvariable=fnamevalue, borderwidth=2)
fnamentry.place(x=250, y=35)
sentry = Entry(f1, relief=RIDGE, textvariable=snamevalue, borderwidth=2)
sentry.place(x=250, y=60)
apentry = Entry(f1, relief=RIDGE, textvariable=apvalue, borderwidth=2)
stentry = Entry(f1, relief=RIDGE, textvariable=stsvalue, borderwidth=2)
apentry.place(x=250, y=85)
stentry.place(x=250, y=110)
datentry = DateEntry(f1, relief=RIDGE, selectmode='day', textvariable=datevalue)
datentry.place(x=260, y=135)

    # global getvalg
def getval():
     mydb = dic.connect(host='localhost', user='root', password='', database='csc')
     try:
        s = "INSERT INTO haryana (Name,Father_Name, Service_Name, Application_Number,Submission_Date, " \
                "Status) VALUES(%s, %s, %s, %s, %s, %s) "
        val = (namevalue.get(), fnamevalue.get(), snamevalue.get(), apvalue.get(), datevalue.get(), stsvalue.get())
        cur = mydb.cursor()
        cur.execute(s, val)
        mydb.commit()
            # lastid = cur.lastrowid
        messagebox.showinfo('Information', 'Record Saved Successfully.\nClose the Window')

        namentry.delete(0, END)
        fnamentry.delete(0, END)
        sentry.delete(0, END)
        apentry.delete(0, END)
        stentry.delete(0, END)
        namentry.focus_set()


     except Exception as e:

        print(e)
        mydb.rollback()
        mydb.close()


submit = Button(f1, text="Submit", relief=RIDGE,  command=getval)
submit.place(x=260, y=165)
def show():
    mydb = dic.connect(host='localhost', user='root', password='', database='csc')
    cur = mydb.cursor()
    cur.execute("SELECT Sr_No, Name, Father_Name,Service_Name, Application_Number, Status FROM haryana")
    haryana = cur.fetchall()
    print(haryana)

    for i, (Sr_No, Name, Father_Name, Service_Name, Application_Number, Status) in enumerate(haryana, start=1):
        lst.insert("", "end", values(Sr_No, Name, Father_Name, Service_Name, Application_Number, Status))
        mydb.close()

cols= ('Sr_No.', 'Name', 'Father_Name','Service Name','Application_Number','Date','Status')
lst=ttk.Treeview(f1, column=cols, show="headings")
for col in cols:
    lst.heading(col, text=col)
    # lst.grid(row=1, column=0, columnspan=2)
    lst.place(x=10, y=100)
# show()
mainmenu = Menu(root)
m1 = Menu(mainmenu, tearoff=0)
# m1.add_command(label="Record")
m1.add_command(label="Save")
mainmenu.add_cascade(label="File", menu=m1)
m2 = Menu(mainmenu, tearoff=0)
m2.add_command(label="Welcome")
m2.add_command(label="Feedback")
m3 = Menu(mainmenu, tearoff=0)
mainmenu.add_cascade(label="Saral Haryana", menu=m3)
m3.add_command(label="Submit Data")
mainmenu.add_cascade(label="Help", menu=m2)
submenu = Menu(mainmenu, tearoff=0)
m1.add_separator()
m1.add_cascade(label="Record", menu=submenu)
m1.add_separator()
submenu.add_command(label="PVC")
submenu.add_command(label="Aadhar Card")
submenu.add_command(label="All Record")
m1.add_command(label="Exit", command=root.destroy)
root.config(menu=mainmenu)
l1 = Label(f2, text="DIGITAL SEWA KENDRA, PUR", fg="white", bg="RED", font="comicsansms 20 bold")
l1.pack(pady=5, padx=5)
l2 = Label(f4, text="Cont:- Bintu Jangra: 9992518092, Sahil: 9306538685", fg="red", font="comicsansms 15 bold", padx=5)
l2.pack()

mainloop()
